name: "Check If"

on:
  workflow_dispatch:
    inputs:
      cdn:
        type: boolean
        description: 'Upload assets to CDN'
        required: true
        default: false

jobs:
  check-if:
    runs-on: ubuntu-latest

    steps:
      # release assets to CDN
      - name: Upload external assets to CDN
        if: ${{ github.event.inputs.cdn }}
        id: upload-cdn
        run: |
          echo "Call when cdn true"