name: "Monitor Changed Files"

on:
  workflow_dispatch:
  pull_request:
      branches:
        - main
      types:
        - opened
        - synchronize
        - reopened
        - ready_for_review
        - edited

jobs:
  run-monitor-changed-files:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      
      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v40
        with:
          files_yaml_from_source_file: .github/files-in-observation.yml
      
      - name: Send Slack Notification
        if: steps.changed-files-yaml.outputs.seo_any_changed == 'true'
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HOOK }}
        with:
          # slack format: https://api.slack.com/reference/surfaces/formatting#basics
          payload: |
            {
              "text": "Hey <!subteam^S017VDRG26R>, files that have changed in PR https://github.com/${{github.repository}}/pull/${{ github.event.pull_request.number }}: ${{ steps.changed-files-yaml.outputs.seo_all_changed_files }}"
            }